const TRIVIA_DATA = [
    {
        question: "Which language runs in a web browser?",
        a: "Java",
        b: "C",
        c: "Python",
        d: "JavaScript",
        correct: "d",
    },
    {
        question: "What does CSS stand for?",
        a: "Central Style Sheets",
        b: "Cascading Style Sheets",
        c: "Cascading Simple Sheets",
        d: "Cars SUVs Sailboats",
        correct: "b",
    },
    {
        question: "What does HTML stand for?",
        a: "Hypertext Markup Language",
        b: "Hypertext Markdown Language",
        c: "Hyperloop Machine Language",
        d: "Helicopters Terminals Motorboats Lamborginis",
        correct: "a",
    },
    {
        question: "What year was JavaScript launched?",
        a: "1996",
        b: "1995",
        c: "1994",
        d: "none of the above",
        correct: "b",
    },
    {
        question: "Inside which HTML element do we put the Javascript?",
        a: "<js>",
        b: "<script>",
        c: "javascript",
        d: "scripting",
        correct: "b",
    },
    {
        question: "Where is the correct place to insert a JavaScript?",
        a: "The <head> section",
        b: "Both the <head> section and the <body> section are correct",
        c: "The <body> section",
        d: "In the <aside> section",
        correct: "b",
    },
    {
        question: "What is the correct syntax for referring to an external script called 'xxx.js'?",
        a: "<script src='xxx.js'>",
        b: "<script name='xxx.js'>",
        c: "<script href='xxx.js'>",
        d: "<script alt='xxx.js'>",
        correct: "a",
    },
    {
        question: "How do you write 'Hello World' in an alert box?",
        a: "msg('Hello World');",
        b: "alertBox('Hello World');",
        c: ' msgBox("Hello World");',
        d: ' alert("Hello World");',
        correct: "d",
    },
    {
        question: "How do you create a function in Javascript?",
        a: "function:myFunction()",
        b: "function myFunction()",
        c: "function = myFunction()",
        d: "function > myFunction()",
        correct: "c",
    },
    {
        question: "How do you call a function named 'myFunction'?",
        a: "myFunction()",
        b: "function myFunction()",
        c: "call myFunction()",
        d: "call function = myFunction()",
        correct: "a",
    },
    {
        question: "How to write an IF statement in Javascript?",
        a: "if(i == 5)",
        b: "if i == 5 then",
        c: "if i = 5 then",
        d: "if i = 5",
        correct: "a",
    },
    {
        question: "How to write an IF statement for executing some code if 'i' is NOT equal to 5?",
        a: "if (i <> 5)",
        b: "if i=! 5 then",
        c: "if i !=5",
        d: "if (i <> 5)",
        correct: "c",
    },
    {
        question: "How does a WHILE loop start?",
        a: "while i = 1 to 10",
        b: "while (i <= 10)",
        c: "while (i <= 10; i++)",
        d: "while = (i<= 10)",
        correct: "b",
    },
    {
        question: "How does a FOR loop start?",
        a: "for i = 1 to 5",
        b: "for (i = 0; i <= 5)",
        c: "for (i <= 5; i++)",
        d: "for (i = 0; i <= 5; i++)",
        correct: "d",
    },
    {
        question: "How can you add a comment in a JavaScript?",
        a: "<!--This is a comment-->",
        b: "/This is a comment",
        c: "'This is a comment'",
        d: "<This is a comment>",
        correct: "a",
    },
];

export default TRIVIA_DATA